Scroll to the first line when the preview hits top
asciidoctor/asciidoctor-vscode pull request #475
Opened 2021-10-31 18:35 UTC by Mogztter

Since the document title does not have a `data-line` attribute when we scroll to the top on the preview it does not scroll to the document title (but to the first block).

I didn't find a way to do the opposite (i.e., when we scroll to the top of the AsciiDoc document, scroll to the top of the preview). The reason is that we cannot tell what is on the first line. I guess we could read the first line and check if it's the document title but even then the document title could be hidden in the preview with `:showtitle!:`.

So this pull request partially fixes #348

2021-10-31 18:37 UTC, Mogztter commented
> I didn't find a way to do the opposite (i.e., when we scroll to the top of the AsciiDoc document, scroll to the top of the preview). The reason is that we cannot tell what is on the first line. I guess we could read the first line and check if it's the document title but even then the document title could be hidden in the preview with :showtitle!:.

Arguably, we could scroll to top no matter what... I think this is the expected behavior anyway. Thoughts?

2021-11-03 06:44 UTC, danyill requested changes
A little niggardly, I admit.

2021-11-03 06:44 UTC, danyill commented on preview-src/index.ts
> +        messaging.postMessage('revealLine', { line: 1 })
I think lines are indexed beginning at `0` :stuck_out_tongue_winking_eye: 

When I had `1` My source document line stopped at line `2` when I was at the top of the preview.

We gaze upon our tooltip assistance and see it is zero-indexed:

![image](https://user-images.githubusercontent.com/674783/140018697-40e87058-b0b0-4d8d-9232-0b856c164458.png)

2021-11-03 06:44 UTC, danyill commented on preview-src/index.ts
> +        messaging.postMessage('revealLine', { line: 1 })
```suggestion
        messaging.postMessage('revealLine', { line: 0 })
```

2021-11-03 06:52 UTC, danyill commented
> > I didn't find a way to do the opposite (i.e., when we scroll to the top of the AsciiDoc document, scroll to the top of the preview). The reason is that we cannot tell what is on the first line. I guess we could read the first line and check if it's the document title but even then the document title could be hidden in the preview with :showtitle!:.
> 
> Arguably, we could scroll to top no matter what... I think this is the expected behavior anyway. Thoughts?

I am not sure, I probably wouldn't put much effort into it. I don't think the preview and source should be "perfect" because the underlying alignment is not 1-to-1 (we have hidden things, comments, document attributes etc.).

I am concerned about side effects and jumping back and forth for a single line change for large document headers. There is already a problem like this at the _bottom_ of some documents which I've experienced where the preview and source pane flutter alarmingly whenever you scroll below a particular point. On small form factors or when the window isn't maximized this could be an issue, perhaps when you scroll after the title or after the document attributes or to the first `data-line-x` value.

We also have this problem for tables where which cross more than one screen because we can't allocate `data-line-x` on the table cells or rows.

I guess the proof would be to implement it and see if it can be made suitably robust.

2021-11-03 08:12 UTC, Mogztter commented
> I am not sure, I probably wouldn't put much effort into it. I don't think the preview and source should be "perfect" because the underlying alignment is not 1-to-1 (we have hidden things, comments, document attributes etc.).

That's true but when the scrollbar hits the top (or the bottom) it should also hits the top (or the bottom) of the preview/editor.

> I am concerned about side effects and jumping back and forth for a single line change for large document headers. There is already a problem like this at the bottom of some documents which I've experienced where the preview and source pane flutter alarmingly whenever you scroll below a particular point. On small form factors or when the window isn't maximized this could be an issue, perhaps when you scroll after the title or after the document attributes or to the first data-line-x value.

Here's the result:

![jump](https://user-images.githubusercontent.com/333276/140025410-12fcd85f-91aa-41e9-95ba-c081fa5d3216.gif)

Not sure if it's possible but we could "smooth scroll" instead of "jumping".

In my opinion, today it's even worse since you cannot have both scrollbars at the top (i.e., show the document title on both the preview and the editor):

![showtitle](https://user-images.githubusercontent.com/333276/140026119-5ccc8132-c8e1-4c43-bf9a-1d94f257e51c.gif)

> We also have this problem for tables where which cross more than one screen because we can't allocate data-line-x on the table cells or rows.

As far as I know this improvement does not improve or worsen the situation regarding tables.
We can address this concern but not as part of this pull request since that's another issue.

> I guess the proof would be to implement it and see if it can be made suitably robust.

I did and I think it's better, now both sides will be synced when they reach the top.

2021-11-03 08:21 UTC, Mogztter commented on preview-src/index.ts
> +        messaging.postMessage('revealLine', { line: 1 })
Good catch!

2021-11-06 05:36 UTC, danyill commented
> I did and I think it's better, now both sides will be synced when they reach the top.

I agree, thanks for this! Let's do it.

2021-11-06 05:37 UTC, danyill approved these changes

2021-11-06 05:39 UTC, merged